// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package abele.samples.newactivity.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("abele.samples.newactivity.domain.Owner")
@ServiceName("abele.samples.newactivity.domain.Owner")
public interface OwnerRequest extends RequestContext {

    abstract Request<java.lang.Long> countOwners();

    abstract Request<java.util.List<abele.samples.newactivity.client.managed.request.OwnerProxy>> findAllOwners();

    abstract Request<java.util.List<abele.samples.newactivity.client.managed.request.OwnerProxy>> findOwnerEntries(int firstResult, int maxResults);

    abstract Request<abele.samples.newactivity.client.managed.request.OwnerProxy> findOwner(Long id);

    abstract InstanceRequest<abele.samples.newactivity.client.managed.request.OwnerProxy, java.lang.Void> remove();

    abstract InstanceRequest<abele.samples.newactivity.client.managed.request.OwnerProxy, java.lang.Void> persist();
}
