// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package abele.samples.newactivity.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("abele.samples.newactivity.domain.Pet")
@ServiceName("abele.samples.newactivity.domain.Pet")
public interface PetRequest extends RequestContext {

    abstract Request<java.lang.Long> countPets();

    abstract Request<java.util.List<abele.samples.newactivity.client.managed.request.PetProxy>> findAllPets();

    abstract Request<java.util.List<abele.samples.newactivity.client.managed.request.PetProxy>> findPetEntries(int firstResult, int maxResults);

    abstract Request<abele.samples.newactivity.client.managed.request.PetProxy> findPet(Long id);

    abstract InstanceRequest<abele.samples.newactivity.client.managed.request.PetProxy, java.lang.Void> remove();

    abstract InstanceRequest<abele.samples.newactivity.client.managed.request.PetProxy, java.lang.Void> persist();
}
